= Livros Recomendados
:toc: left
:language: asciidoc
:docref: link:/docs

Alguns livros recomendados com um breve resumo

== Algoritmos Funcionais: Introdução minimalista à logica de programação funcional pura aplicada à teoria dos conjuntos

=== Onde comprar?
- https://amzn.to/34XxRSr[Amazon]
- https://www.altabooks.com.br/produto/algoritmos-funcionais/[Alta Books]

== Leitura
- _Status_: 34/213

=== Resenha
N/A

== Como ser um Programador Melhor: um Manual Para Programadores que se Importam com Código 

=== Onde comprar?
- https://amzn.to/3aTZsrv[Amazon]

=== Leitura
- _Status_: 118/374

=== Resenha

O livro irá abordar temas em todas as áreas do desenvolvimento. Desde como você organiza seu código até como fazer debug. Super recomendado.


== Domain-Driven Design: Atacando as Complexidades no Coração do Software

=== Onde comprar?
- https://amzn.to/3mVmXms[Amazon]

=== Leitura
- _Status_: 116/484

=== Resenha
O livro é excelente. Irá tratar do Design do seu código. Te ajudará a responder perguntas como: 

* O que é domínio?
* Como dar nomes as classes? Esses nomes tem relação com o domínio da aplicação?
* Como faço a separação de funcionalidades?

O primeiro tópico do livro vai tratar de Linguagem Onipresente, em resumo precisamos construir uma linguagem onipresente ao desenvolver software. Desenvolvedores e Analistas de negócio não falam a mesma linguagem, mas termos e ações precisam ser definidos para ambos estarem alinhados.

== The Pragmatic Programmer: your journey to mastery
=== Onde comprar?
- https://amzn.to/3rIqbgT[Amazon]

=== Leitura
- _Status_: 174/352

=== Resenha

O livro irá focar na filosofia de vida de um desenvolvedor. Não é um livro que te ensinará técnicas de desenvolvimento, mas te dará insights muitos valiosos para sua vida profissional. Um que eu já conhecia era o "_Don't live a broken window_" que é a filosofia de sempre consertar os erros que são visiveis em um projeto. Quanto mais erros em um projeto, mais a moral do time vai ser abalada e mais erros o time gerará. **Recomendado!!**
