= Livros Recomendados
:toc: left
:toclevels: 1
:language: asciidoc
:docref: link:/docs

Alguns livros recomendados com um breve resumo. Você verá que muitos deles estão com a leitura incompleta, sim! Isso, eu assumo que deixo leituras e vou ler livros novos, e depois volto.

== Algoritmos Funcionais: Introdução minimalista à logica de programação funcional pura aplicada à teoria dos conjuntos

=== Onde comprar?
- https://amzn.to/34XxRSr[Amazon]
- https://www.altabooks.com.br/produto/algoritmos-funcionais/[Alta Books]

=== Leitura
- _Status_: 34/213

=== Resenha
N/A

== An Introduction to Lte: Lte, Lte-Advanced, Sae, Volte and 4g Mobile Communications

=== Onde comprar?
- https://amzn.to/2JvohyK[Amazon]

=== Leitura
- _Status_: 486/486 

=== Resenha

Detalha toda infraestrutura da comunicação 4G. Foi muito útil para eu conseguir entender como funciona a rede e quais os desafios que iria encarar ao migrar minha carreira para Engenheiro Telecom/Computação. Para quem vai trabalhar com sinais é bem detalhado, mas para quem vai detalhar com os fluxo de Charging/Policy não é detalhado.

== Como ser um Programador Melhor: um Manual Para Programadores que se Importam com Código 

=== Onde comprar?
- https://amzn.to/3aTZsrv[Amazon]

=== Leitura
- _Status_: 118/374

=== Resenha

O livro irá abordar temas em todas as áreas do desenvolvimento. Desde como você organiza seu código até como fazer debug. Super recomendado.

== Distributed Systems

=== Leitura
- _Status_: 152/598 

=== Onde comprar?
- https://amzn.to/381XvY4[Amazon]

=== Resenha

Livro texto de praticamente toda matéria de sistemas distribuidos. Como eu NÃO tive essa matéria na UNICAMP, resolvi ler. Excelente, irá detalhar todos os desafios de se construir sistemas distribuídos. Recomendável para qualquer desenvolvedor backend que quer ter ciência do real desafio.

== Domain-Driven Design: Atacando as Complexidades no Coração do Software

=== Onde comprar?
- https://amzn.to/3mVmXms[Amazon]

=== Leitura
- _Status_: 116/484

=== Resenha
O livro é excelente. Irá tratar do Design do seu código. Te ajudará a responder perguntas como: 

* O que é domínio?
* Como dar nomes as classes? Esses nomes tem relação com o domínio da aplicação?
* Como faço a separação de funcionalidades?

O primeiro tópico do livro vai tratar de Linguagem Onipresente, em resumo precisamos construir uma linguagem onipresente ao desenvolver software. Desenvolvedores e Analistas de negócio não falam a mesma linguagem, mas termos e ações precisam ser definidos para ambos estarem alinhados.

== Introdução à arquitetura de design de software

=== Onde comprar?
- https://amzn.to/38L1W93[Amazon] 

=== Leitura
- _Status_: 280/280

=== Resenha 

O livro é sobre Arquitetura Java. Apesar de precisa de uma atualização, ainda é valido por apresentar um pouco de como a JVM funciona e de alguns padrões que são bem utilizados. Recomendável para quem deseja ser Arquiteto Java.

== Microsserviços Prontos Para a Produção: Construindo Sistemas Padronizados em uma Organização de Engenharia de Software

=== Onde comprar?
- https://amzn.to/2WZETSi[Amazon]

=== Leitura
- _Status_: 88/224

=== Resenha

O livro irá focar no que é necessário para se colocar um microserço em produção. Não há padrão de microserviços, mas há um bom detalhamento do que Escalabilidade/Observalidade. Também ajudará a construir um checklist de como avaliar seu microserviços. Altamente recomendável para quem é Arquiteto de Software.

== O Mítico Homem-mês: Ensaios Sobre Engenharia de Software

=== Onde comprar?
- https://amzn.to/38RNvjH[Amazon]

=== Leitura
- _Status_: NaN/320

=== Resenha

O livro trará uma série de artigos sobre Engenheria de Software. Muitos deles são históricos e alguns você até já conhece por serem praticamente mitologicos. Já ouviu a frase _Não existe bala de prata_, pois é, é um artigo. Muito recomendável para qualquer um que vá se aventurar pela gerência de projetos de desenvolvimento de software. Se seu Agile Coach não leu, fala que ele não manja de nada!

== O Projeto Fênix: um Romance Sobre TI, DevOps e Sobre Ajudar o seu Negócio a Vencer

=== Onde comprar?
- https://amzn.to/3aRdlH3[Amazon]

=== Leitura
- _Status_: 384/384 

=== Resenha
É um livro sensacional! Quem quer conhecer DevOps deve ler ele. Ao começar pensava que esses conceitos eram nativos da Computação, mas vi que são conceitos da industria aplicados a computação. Esse livro vai ter dar uma boa visão desses conceitos e como eles podem ser aplicados. Você não vai aprender nada prático, mas será muito mais útil do que você imagina. **Recomendável!!!**

== The Art of Computer Programming
=== Onde comprar?
- https://amzn.to/2KFLT4x[Amazon]

=== Leitura
- _Status_: NaN/3168

=== Resenha

É uma obra prima. Comprei a primeira edição dele e era voltada para explicar como o processador lidava com linguagem de máquina. Falava de como contas são feitas usando números binários. Mas ao comprar a edição _ainda não definitiva_ levei um susto, a primeira edição foi transformada para falar de algoritmos! Muito válido, mas recomendo só se você quer se tornar o Mestre Jedi Supremo.

== The Pragmatic Programmer: your journey to mastery
=== Onde comprar?
- https://amzn.to/3rIqbgT[Amazon]

=== Leitura
- _Status_: 174/352

=== Resenha

O livro irá focar na filosofia de vida de um desenvolvedor. Não é um livro que te ensinará técnicas de desenvolvimento, mas te dará insights muitos valiosos para sua vida profissional. Um que eu já conhecia era o "_Don't live a broken window_" que é a filosofia de sempre consertar os erros que são visiveis em um projeto. Quanto mais erros em um projeto, mais a moral do time vai ser abalada e mais erros o time gerará. **Recomendado!!**
